// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_kqVEwa8JvTU6vtZhv2oq_JmQZcSof7Q',
    appId: '1:913913512365:web:7f0e2acc27ab8905a3e124',
    messagingSenderId: '913913512365',
    projectId: 'red-height-345703',
    authDomain: 'red-height-345703.firebaseapp.com',
    storageBucket: 'red-height-345703.appspot.com',
    measurementId: 'G-Z7KCEP86F3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_PLR9j98p7acDC_dNqv7I7zoWXXntdX8',
    appId: '1:913913512365:android:631128b3b757a1cba3e124',
    messagingSenderId: '913913512365',
    projectId: 'red-height-345703',
    storageBucket: 'red-height-345703.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqPVs1gl4S_bObNPiLp1VjzjO2VsM6yVI',
    appId: '1:913913512365:ios:ed4788bb1f3bc45aa3e124',
    messagingSenderId: '913913512365',
    projectId: 'red-height-345703',
    storageBucket: 'red-height-345703.appspot.com',
    iosBundleId: 'newscartz.com.example.newscartz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqPVs1gl4S_bObNPiLp1VjzjO2VsM6yVI',
    appId: '1:913913512365:ios:48de6c4ad7f182d3a3e124',
    messagingSenderId: '913913512365',
    projectId: 'red-height-345703',
    storageBucket: 'red-height-345703.appspot.com',
    iosBundleId: 'newscartz.com.example.newscartz.RunnerTests',
  );
}
